version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    container_name: teslamate
    restart: always
    networks:
      - proxy
    depends_on:
      - database
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=tesla_db
      - MQTT_HOST=tesla_mosquitto
      - VIRTUAL_HOST=${TM_DOMAIN}
      - CHECK_ORIGIN=true
      - TZ=${TM_TZ}
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.teslamate.entrypoints=http"
      - "traefik.http.routers.teslamate.rule=Host(`${TM_DOMAIN}`)"
      - "traefik.http.routers.teslamate.middlewares=headers,redirectregex,https-redirect,"
      - "traefik.http.routers.teslamate-secure.entrypoints=https"
      - "traefik.http.routers.teslamate-secure.rule=Host(`${TM_DOMAIN}`) && Path(`/live/websocket`)"
      - "traefik.http.routers.teslamate-secure.tls=true"
      - "traefik.http.routers.teslamate-secure.tls.certresolver=http"
      - "traefik.http.routers.teslamate-secure.service=teslamate"
      - "traefik.http.services.teslamate.loadbalancer.server.port=4000"

  database:
    image: postgres:13
    container_name: tesla_db
    restart: always
    networks:
      - proxy
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=teslamate
    volumes:
      - ${HOME}/Data/teslamate/postgres:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    container_name: tesla_grafana
    restart: always
    networks:
      - proxy
    user: "1000"
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=tesla_db
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_DOMAIN=${TM_DOMAIN}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - 3000:3000
    volumes:
      - ${HOME}/Data/teslamate/grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`${TM_DOMAIN}`)"
      - "traefik.http.routers.grafana.middlewares=headers,redirectregex,https-redirect,"
      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.rule=Host(`${TM_DOMAIN}`) && (Path(`/grafana`) || PathPrefix(`/grafana/`))"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=http"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=4000"

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: tesla_mosquitto
    restart: always
    networks:
      - proxy
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - ${HOME}/Data/teslamate/mosquitto/conf:/mosquitto/config
      - ${HOME}/Data/teslamate/mosquitto/data:/mosquitto/data

networks:
  proxy:
    external: true
